name: Build

on: [ push, pull_request, workflow_dispatch ]

env:
  CI:

jobs:
  build:
    name: Build
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: gradle/wrapper-validation-action@v1
      - uses: gradle/gradle-build-action@v2
      - name: Build
        run: ./gradlew :desktopApp:packageReleaseStripArchitecture
      - name: Upload distributable
        uses: actions/upload-artifact@v3
        with:
          name: Distributable
          path: |
            desktopApp/build/distributable/
